// <auto-generated />
using System;
using CompanyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241028210808_ImplementBranchModelDatabase")]
    partial class ImplementBranchModelDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyAPI.ViewModel.AreaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Expense")
                        .HasColumnType("float");

                    b.Property<int>("LinkedBranchId")
                        .HasColumnType("int");

                    b.Property<string>("NameArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LinkedBranchId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.BranchModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyLinkedID")
                        .HasColumnType("int");

                    b.Property<double>("Expense")
                        .HasColumnType("float");

                    b.Property<string>("HeadOffice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyLinkedID");

                    b.ToTable("Branchs");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.CompanyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Expense")
                        .HasColumnType("float");

                    b.Property<double>("MonthyBilling")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("BranchModelId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.EquipmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("BranchModelId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.AreaModel", b =>
                {
                    b.HasOne("CompanyAPI.ViewModel.BranchModel", "LinkedBranch")
                        .WithMany("Areas")
                        .HasForeignKey("LinkedBranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedBranch");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.BranchModel", b =>
                {
                    b.HasOne("CompanyAPI.ViewModel.CompanyModel", "CompanyLinked")
                        .WithMany("Branch")
                        .HasForeignKey("CompanyLinkedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyLinked");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.EmployeeModel", b =>
                {
                    b.HasOne("CompanyAPI.ViewModel.AreaModel", "Area")
                        .WithMany("Employees")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyAPI.ViewModel.BranchModel", null)
                        .WithMany("Employees")
                        .HasForeignKey("BranchModelId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.EquipmentModel", b =>
                {
                    b.HasOne("CompanyAPI.ViewModel.AreaModel", "Area")
                        .WithMany("Equipments")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyAPI.ViewModel.BranchModel", null)
                        .WithMany("Equipments")
                        .HasForeignKey("BranchModelId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.AreaModel", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.BranchModel", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Employees");

                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("CompanyAPI.ViewModel.CompanyModel", b =>
                {
                    b.Navigation("Branch");
                });
#pragma warning restore 612, 618
        }
    }
}
